mxz7/nypsi

commands/blackjack.js
commands/coinflip.js
commands/highlow.js
commands/minesweeper.js
commands/pay.js
commands/prestige.js
commands/roulette.js
commands/slots.js
commands/vote.js
economy/utils.js
guilds/utils.js

better balanced gambling
prevention for paying new alts
prestige / xp limit
10% vote bonus

update master branch with changes

---

commands/addemoji.js

support for urls and attachments as well as changing the name

upgraded addemoji

---

commands/botstats.js
commands/mentions.js
commands/nowplaying.js
commands/recenttracks.js
events/message.js
nypsi.js
utils/classes/EmbedBuilders.js
utils/database/database.js
utils/users/utils.js

frees up memory, and allows mentions to transfer between restarts

mentions are now stored in the database

---

commands/buy.js
commands/clearinventory.js
commands/execsql.js
commands/mine.js
commands/sell.js
commands/sellall.js
commands/shop.js
commands/smelt.js
commands/use.js
package-lock.json
package.json
utils/economy/items.json
utils/economy/utils.js
utils/imghandler.js

adds minecraft based items, $mine, $smelt and other little changes
added clear inventory command, fixed some inventory bugs, made execsql better.

minecraft items update

---

commands/yablon.js

basic yablon game, might add more obscure rules later

add yablon game

---

commands/karmashop.js
utils/premium/utils.js

style: prettier formatting

---

commands/streetrace.js
utils/economy/items.json

allows anyone to join street races and use a cycle instead of a car

feat: add cyclist for street race

---

.commitlintrc.json
.gitignore
.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

lint commit messages with husky pre commit hooks

ci: lint commit messages 

---

src/utils/workers/mentions.ts

fix: worker mentions use encryption

---

src/utils/imghandler.ts

feat: add more cats subreddits

---

package-lock.json
package.json
src/utils/functions/member.ts
src/utils/workers/choosemember.ts

* only when there's over 1k members in the server to prevent long loops

feat: use worker for getmember* to (hopefully) improve performance

---

src/commands/coinflip.ts

refactor: coinflip improvements

---

.gitignore
setup.sh
src/commands/profile.ts
src/utils/commandhandler.ts
src/utils/database/database.ts
src/utils/users/utils.ts

change $profile command to allow users to request their data

feat: profile command data request

---

src/commands/profile.ts

makes it more clear you're talking about their data and not just the data stored in the nypsi database

fix: english error

---

src/nypsi.ts
src/utils/economy/utils.ts
src/utils/scheduled/votehandler.ts

seperate vote handler from economy utils

feat: vote handler

---

src/commands/guild.ts
src/commands/yablon.ts

tried making a guild help command, hope it's good enough i'm not really the best at this

feat: guild help command

---

src/index.ts
src/utils/functions/heartbeat.ts
src/utils/models/Client.ts

prevents a single cluster from being stuck & resulting in massive delays or simply being offline

feat: add heatbeat system

---

src/commands/profile.ts

feat: add expire message to profile

---

src/commands/f.ts

fixes an issue where it wouldn't defer the reply well and show a "This interaction failed" error
Also fixes an issue when there's multiple f commands it won't function because the ID is the same so if you click on one button you can't click on another

fix: interaction failed

---

src/utils/commandhandler.ts

testing didnt function properly so dont know if it works

refactor: require external emojis permission

---

src/events/message.ts
src/utils/moderation/utils.ts

i think i did it right this time (my brain hurts)

feat: add channel to filter violation mod log

---

.github/workflows/ci.yml
src/commands/raffle.ts
src/commands/stats.ts
src/utils/economy/utils.ts
src/utils/scheduled/clusterjobs/lottery.ts

this adds "tickets" to the lottery cancel message, otherwise the message is broken as it's somewhat unclear that you're referring to tickets

fix: english error (lottery cancel message)

---

src/commands/deletemydata.ts

i don’t think u need a description

fix: new english typo

---

package-lock.json
package.json
prisma/schema.prisma
src/commands/logs.ts
src/events/channelCreate.ts
src/events/channelDelete.ts
src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/events/messageDelete.ts
src/events/messageDeleteBulk.ts
src/events/messageUpdate.ts
src/utils/models/Client.ts
src/utils/models/GuildStorage.ts
src/utils/moderation/utils.ts
src/utils/scheduled/clusterjobs/moderationchecks.ts

adds very very basic logs (planned to be added on to and updated in future)

feat: logs

---

src/events/messageDeleteBulk.ts
src/utils/functions/date.ts

preview:
(also simplified some code in date.ts)

feat: add time and channel name to bulk delete log

---

package-lock.json
package.json
src/commands/auction.ts
src/commands/buy.ts
src/commands/sell.ts
src/commands/use.ts
src/events/interactionCreate.ts
src/utils/economy/utils.ts

also includes better slash command support for auctions
& added support for buy/sell

feat: item autocomplete

---

src/utils/scheduled/scheduler.ts

change daily streak reset time from 12:01am to 11:59pm

refactor: change daily streak scheduled time

---

data/achievements.json
src/commands/fight.ts
src/utils/scheduled/clusterjobs/lottery.ts
src/utils/votehandler.ts

feat: add more achievements

---

prisma/schema.prisma
src/commands/ecoban.ts
src/utils/commandhandler.ts
src/utils/economy/utils.ts

feat: add duration to eco bans

---

src/commands/bdsm.ts

description blah blah read the title

fix: bdsm counts toward horny achievement

---

data/items.json

updated the rarity of warehouse permit item from 2 to 1

refactor: warehouse permit rarity change

---

src/commands/workers.ts

reorder the claim embed to be ordered by earnings instead of prestige requirement

refactor: reorder claim embed

---

data/items.json

I have no idea if this will be in the same branch as the other one or if it'll pass prettier but uh pretend it does both of those things

feat: launchpad upgrade

---

package-lock.json
package.json
src/commands/reseteco.ts
src/utils/functions/captcha.ts
src/utils/handlers/commandhandler.ts

use captcha-canvas to provide image captchas instead of text

feat: better captchas

---

src/scheduled/clusterjobs/workers.ts
src/scheduled/jobs/votereminders.ts
src/types/Notification.ts
src/utils/functions/economy/auctions.ts
src/utils/functions/economy/boosters.ts
src/utils/functions/users/notifications.ts
src/utils/handlers/notificationhandler.ts

easier dx than using redis key

refactor: notification queue function

---

data/items.json
src/commands/auction.ts
src/commands/bake.ts

feat: grandma booster

---

data/items.json
src/utils/functions/economy/balance.ts
src/utils/functions/economy/inventory.ts

add highroller booster
maxbet limit is 1m without boosters

feat: maxbet booster

---

data/workers.json

increase the launchpad effect from 0.75 to 1.2

refactor: improve launchpad

---

data/items.json

adds more aliases to items, to make a lot of them easier to type.

refactor: aliases

---

data/achievements.json
src/types/Economy.ts
src/utils/functions/economy/achievements.ts
src/utils/functions/economy/xp.ts
src/utils/handlers/commandhandler.ts

feat: achievement dms

---

package-lock.json
package.json
src/commands/top.ts
src/utils/functions/color.ts
src/utils/functions/economy/top.ts

adds page system to top commands

feat: upgrade top commands

---

src/events/message.ts

change the dm support message to be more clear to people with 2iq who don't know what talking to a human is

refactor: support request message

---

data/lists.json

adds more messages to the $work command
because they're funny and i was bored

feat: work messages

---

package-lock.json
package.json
prisma/schema.prisma
src/commands/role.ts
src/events/guildMemberAdd.ts
src/events/interactionCreate.ts
src/models/Client.ts
src/utils/functions/guilds/roles.ts
src/utils/functions/member.ts

adds /role command
autojoin roles

feat: role utils

---

src/commands/prestige.ts

change the prestige command to show more detail including your current xp and how much more is needed to prestige i coded this on my phone so im 99% sure it's gonna fail prettier

feat: show xp needed to prestige

---

package-lock.json
package.json
src/commands/bake.ts
src/commands/blackjack.ts
src/commands/highlow.ts
src/commands/mines.ts
src/commands/rps.ts
src/commands/slots.ts
src/commands/streetrace.ts
src/scheduled/clusterjobs/lottery.ts
src/utils/functions/economy/items/stolen_credit_card.ts
src/utils/functions/random.ts

replace some important things with crypto random module

feat: crypto random

---

prisma/schema.prisma
src/commands/bankrob.ts
src/commands/blackjack.ts
src/commands/coinflip.ts
src/commands/deletemydata.ts
src/commands/fight.ts
src/commands/highlow.ts
src/commands/mines.ts
src/commands/requestdata.ts
src/commands/rob.ts
src/commands/roulette.ts
src/commands/rps.ts
src/commands/slots.ts
src/commands/stats.ts
src/commands/viewgame.ts
src/commands/x.ts
src/utils/Constants.ts
src/utils/functions/economy/stats.ts
src/utils/functions/economy/utils.ts
src/utils/logger.ts

feat: game history

---

data/achievements.json
package-lock.json
package.json
src/commands/blackjack.ts
src/commands/highlow.ts
src/commands/mines.ts
src/commands/premium.ts
src/commands/top.ts
src/commands/tower.ts
src/utils/Constants.ts

feat: add dragon tower game

---

src/commands/pay.ts
src/utils/logger.ts

removes the dollar sign from item transactions when logging them

fix: dollar sign from item logging

---

data/achievements.json
data/bakery_upgrades.json
data/items.json
prisma/schema.prisma
src/commands/bake.ts
src/commands/use.ts
src/events/interactionCreate.ts
src/scheduled/clusterjobs/checkauctions.ts
src/types/Economy.ts
src/utils/Constants.ts
src/utils/functions/economy/bakery.ts
src/utils/functions/economy/utils.ts

not really guaranteed. need to see if people would prefer this to the current bake system

feat: cookie clicker type update to /bake

---

src/commands/forcelose.ts

allow moderators to use the forcelose command

feat: mods can use forcelose

---

src/commands/auction.ts

this fixes the issue where people can post auctions more than 10 billion dollars.

fix exploiting auctions (requested by zack)

---

src/commands/x.ts

admin level no longer lies to me

fix: admin level check

---

data/items.json
data/workers.json
package.json
src/commands/workers.ts
src/scheduled/clusterjobs/workers.ts
src/types/Workers.ts
src/utils/functions/economy/workers.ts
src/utils/functions/economy/xp.ts
src/utils/functions/random.ts

worker which provides a seperate (very slow) way to earn gems

feat: quarry worker

---

src/scheduled/clusterjobs/lottery.ts
src/utils/functions/economy/utils.ts
src/utils/handlers/webhookhandler.ts

refactor: adjust lottery ticket price & voting amount

---

src/commands/ecohistory.ts
src/commands/item.ts
src/types/Chart.ts
src/utils/Constants.ts
src/utils/functions/economy/auctions.ts
src/utils/functions/workers/auctionhistory.ts

also improves appearance of graphs

feat: item sale history

---

package.json
src/commands/chatreaction.ts
src/commands/coinflip.ts

feat: open cf/cr games

---

src/events/guildMemberUpdate.ts

im not really sure if i put it in the right place or not, the nickname check and stuff did work on my test bot tho :+1:

feat: add nickname logs

---

src/commands/data.ts

this fixes the **/data** command so the italics actually apply to the message

fix: message syntax

---

src/commands/premium.ts

i have no idea if this will work but uh yes

refactor: allow special characters in custom command

---

src/commands/premium.ts

no more toLowerCase tomfoolery my in custom command

refactor: allow capitals in custom commands

---

src/commands/streetrace.ts

i fucked up so i un fucked it up

fix: speed 0 streetrace

---

src/commands/streetrace.ts

it should work now i hope (i need a better way of testing this dont i)

fix: fixed it again

---

src/commands/streetrace.ts

this is taking embarrassingly long to get working

fix: speed limit 0 still not working

---

src/commands/use.ts

https://www.reddit.com/r/grammar/comments/6nbh7a/is_it_i_have_eaten_or_i_have_ate/
this removes _have ate_ and replaces it with _have eaten_, as it is the correct grammar

fix: correct grammar

---

src/utils/functions/supportrequest.ts

big mod wasnt pinged before so it is now
ta daaaa

fix: add big mod to support request mentions

---

src/commands/premium.ts

this pr just makes it so more people can easily notice the crate shop if they're interested in buying from it

refactor: link crate shop in premium command

---

src/commands/x.ts

this fixes every typo in **$x** that i'm aware of

fix: typos

---

src/commands/addemoji.ts

i'm not 100% sure this will work but this should fix linting warnings if it does

fix: update guild expressions variable

---

src/commands/bluser.ts
src/commands/forcelose.ts
src/commands/logsearch.ts
src/commands/maintenance.ts
src/commands/requestdm.ts

this makes all admin commands actually use the new admin system instead of the old constant ID system

feat: utilise the new admin system

---

package.json
src/commands/bankrob.ts
src/commands/crateall.ts
src/commands/inrole.ts
src/commands/join.ts
src/commands/role.ts
src/commands/server.ts
src/commands/unmute.ts
src/commands/user.ts
src/events/message.ts
src/nypsi.ts
src/utils/functions/chatreactions/stats.ts
src/utils/functions/guilds/utils.ts

most likely made stricter in future this is just to test that it works without errors for the time being

fix(cache): better discordjs caching

---

src/commands/item.ts
src/utils/Constants.ts
src/utils/functions/economy/auctions.ts
src/utils/functions/economy/balance.ts
src/utils/functions/economy/offers.ts

feat: include offer average in item value

---

data/items.json
package.json
src/commands/blackjack.ts
src/commands/fish.ts
src/commands/highlow.ts
src/commands/hunt.ts
src/commands/mine.ts
src/commands/mines.ts
src/commands/rob.ts
src/commands/roulette.ts
src/commands/rps.ts
src/commands/slots.ts
src/commands/tower.ts
src/utils/functions/economy/guilds.ts
src/utils/functions/economy/xp.ts

and made normal xp earnings better? more normalised for lower prestige users = easier to progress

feat: xp for hunt/fish/mine

---

.env.example
package.json
pnpm-lock.yaml
src/commands/avatarhistory.ts
src/commands/wholesome.ts
src/events/userUpdate.ts
src/models/Client.ts
src/scheduled/clusterjobs/random-drops.ts
src/utils/functions/clusters.ts
src/utils/functions/image.ts

feat: use discord for image hosting

---

src/commands/guild.ts
src/commands/role.ts
src/commands/tags.ts
src/commands/top.ts
src/interactions/vote_crates.ts
src/utils/functions/economy/top.ts
src/utils/functions/users/tags.ts
src/utils/handlers/webhookhandler.ts

note: the most itll go to is 150 as thats when lucky achievement stops tracking, but that should be enough

feat: $top lotto

---

data/workers.json

feat: buff gem shard chance

---

src/commands/fish.ts
src/commands/hunt.ts
src/commands/mine.ts
src/interactions/fish.ts
src/interactions/hunt.ts
src/interactions/mine.ts

feat: button on hunt/fish/mine

---

src/commands/guild.ts

works fine for spaces, but other special characters might need to be fixed as well

fix: guilds with spaces failing to make embed

---

data/guild_upgrades.json
package.json
prisma/migrations/20230817131725_guild_this_level/migration.sql
prisma/schema.prisma
src/commands/guild.ts
src/commands/pay.ts
src/utils/functions/economy/bakery.ts
src/utils/functions/economy/guilds.ts
src/utils/functions/economy/inventory.ts
src/utils/handlers/cooldownhandler.ts

only top 4 members of xp and money get rewards
increased rewards
track contribution for current level

feat: guild upgrade rewards

---

src/commands/guild.ts

fix: g shop brokiee

---

src/utils/functions/guilds/filters.ts

definitely your fault and not mine i would never mess anything up

fix: automute vl

---

src/commands/prefix.ts
src/commands/premium.ts
src/interactions/aliases.ts

also prevent ` from being used in $prefix as that can break formatting of multiple things

fix: be able to remove alias thats just $

---

package.json
src/commands/blackjack.ts
src/commands/highlow.ts
src/commands/mines.ts
src/commands/tower.ts
src/utils/functions/economy/top.ts
src/utils/functions/economy/utils.ts

completely refactor how blackjack works under the hood

refactor: blackjack

---

src/commands/x.ts
src/utils/functions/economy/stats.ts

run `$x fixstats` to fix previous ones (yes i tested it)

fix: some draws still counting as losses in total profit

---

src/commands/slut.ts
src/events/entitlementCreate.ts
src/events/entitlementDelete.ts
src/events/entitlementUpdate.ts
src/models/Client.ts
src/utils/functions/premium/premium.ts

need to have it on main bot for testing

feat: add discord entitlement support (maybe?)

---

src/commands/rob.ts
src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/utils/Constants.ts
src/utils/functions/economy/items/lock_pick.ts

pretend an hour happened between these:

feat: rob grace period on joining server

---

prisma/migrations/20240621144431_better_date_username/migration.sql
prisma/schema.prisma
src/commands/avatar.ts
src/commands/avatarhistory.ts
src/commands/find.ts
src/commands/user.ts
src/commands/usernamehistory.ts
src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/events/userUpdate.ts
src/scheduled/jobs/purge.ts
src/utils/Constants.ts
src/utils/functions/page.ts
src/utils/functions/users/commands.ts
src/utils/functions/users/history.ts
src/utils/functions/users/tag.ts
src/utils/functions/users/utils.ts

better username and avatar tracking
done on command

feat: better tracking

---

src/commands/x.ts

feat: show time until unban in $x

---

package.json
src/commands/level.ts
src/commands/profile.ts
src/utils/Constants.ts
src/utils/functions/economy/balance.ts
src/utils/functions/economy/levelling.ts
src/utils/functions/economy/xp.ts
src/utils/handlers/commandhandler.ts

do all calculations then do database calls

refactor: efficient levelling

---

src/commands/auction.ts

i did an auction too low and so i got annoyed that i did it and now woo theres a fix

feat: auction confirmation on low sell

---

src/interactions/vote_crates.ts

- fix error when using vote crates open button

fix: vote crates open button

---

src/scheduled/clusterjobs/random-drops.ts

- fix: add progress to loot drop achievement and task

fix: add progress to loot drop achievement

---

src/scheduled/clusterjobs/crafted.ts
src/utils/functions/economy/crafting.ts
src/utils/functions/economy/inventory.ts
src/utils/functions/economy/loot_pools.ts
src/utils/functions/economy/scratchies.ts

- fix: gem hunter once again increments for crates and random drops
- refactor: add isGem function to check if an item is a gem

fix: gem hunter achivement

---

data/items.json
src/utils/functions/economy/utils.ts

a little gift for bug finders when its not worthy of the tag

feat: gold star

---

src/commands/reply.ts

Adds an auto-reply to the /reply command for 'auto.buyunban'.  
closes #1821

add auto.buyunban reply option

---

src/commands/mines.ts

Small change in mines info menu

Mines info menu change

---

src/utils/functions/economy/items/streak_token.ts
src/utils/functions/economy/utils.ts

also added a little arrow to show what streak was -> is
when using 1, it doesnt give a count of dscratch, same as it was before

feat: be able to use multiple streaks at once

---

src/commands/fish.ts

fix: add to gem hunter when fishing up a gem

---

src/utils/functions/premium/aliases.ts

whoopsies!
idk what i was really thinking when i did that part, in my head i think i was in like a "check everyone's aliases and make a list" function even tho it clearly just was for one person at a time

fix: accidently made everyone have everyones prem aliases

---

src/commands/guild.ts

you also forgot exit in blocked words

feat: add confirmation to $g leave/delete

---

src/interactions/run_daily.ts
src/utils/functions/economy/items/streak_token.ts
src/utils/functions/economy/utils.ts

fix: dont override /daily with streak tokens

---

src/events/message.ts

chatgpt is sometimes a silly guy and doesnt do it right so lets tell people that

add automatic message disclaimer

---

data/notifications.json
prisma/migrations/20250528191504_marketdelay/migration.sql
prisma/schema.prisma
src/commands/settings.ts
src/utils/functions/economy/market.ts

add market dm delay

---

src/commands/offer.ts
src/commands/x.ts

comes with handy `$x fixblock` to remove instances where people have done this (im curious to see how many have)

fix: dont allow blocking self in offers

---

src/commands/x.ts

remove block fix

---

src/commands/stats.ts
src/utils/functions/economy/bakery.ts

if no cakes, wont show cake (ignore no emoji, old version)
if one of the breakdown items have not been used, it wont be shown

feat: $stats bake

---

src/events/message.ts
src/utils/functions/supportrequest.ts

closes #1844
from dm
from server nypsi isnt in
from server nypsi is in
should also work with attachments

feat: show forwarded messages in support requests

---

CHANGELOG.md
src/commands/minecraft.ts
src/commands/stats.ts
src/index.ts
src/models/Client.ts
src/utils/functions/version.ts

use monthly changelog system

---

src/utils/functions/economy/inventory.ts

i agree with other people that if its breakable it should be at least a few more than blue

5 shards instead of 3 for green

---

src/commands/settings.ts
src/utils/functions/economy/market.ts
src/utils/functions/users/notifications.ts

finally found the x0 thing!!
also i put a comment so you dont break my fix again :(

fix: stop x0 sold messages for good, be able to change market confirm, and dont allow negative numbers in preferences

---

CHANGELOG.md
src/commands/bankrob.ts

i also added a "robbing nypsi bank..." for 2s before showing results to prevent it being completely overpowered
i think gold+ instead of silver+ because of how its literally just the button and no other interaction
i also set the anticheat check to after 50 replays instead of 100 like the others, if you think it should be lower we can change that

add play again to bankrob for gold+

---

prisma/migrations/20250707074050_transactions/migration.sql
prisma/schema.prisma
src/commands/give.ts
src/commands/pay.ts
src/commands/x.ts
src/interactions/accept_offer.ts
src/utils/functions/economy/market.ts
src/utils/functions/economy/trade_requests.ts
src/utils/functions/transactions.ts
src/utils/logger.ts

tracks transactions to database, and adds fancy analytics in $x
closes #2019

add transaction logging

---

src/commands/logs.ts
src/commands/modlogs.ts
src/commands/prefix.ts
src/commands/settings.ts
src/utils/functions/moderation/logs.ts

move modlogs and prefix to settings

---

src/utils/functions/economy/item_info.ts

- move loot pool listing to description instead of field in embed to take advantage of longer length limit

fix: avoid field length limit in $i loot pools

---

src/utils/functions/economy/trade_requests.ts

fix: wrong indexes

---

src/utils/functions/economy/market.ts

fix: earned/spent stats for market

---

prisma/migrations/20250713001811_guild_stats_today/migration.sql
prisma/schema.prisma
src/commands/guild.ts
src/scheduled/jobs/purge.ts
src/utils/functions/economy/guilds.ts

stored the same way as per level is, cleared daily in purge job
also simplified down the code to make it easier to maybe add other tabs in the future

feat: daily guild contribution stats

---

src/commands/x.ts

admin 1 example
admin 4 example

disable buttons you dont have permission for in x

---

src/commands/x.ts

now with handy dandy mobile copying

add back old x findid functionality

---

src/commands/chatreaction.ts

Now the buttong should go away after cancelling the duel request

fix: cr duel buttons staying on cancel/deny

---

src/commands/blackjack.ts

test to see if the messages that break actually get a response from message.edit/update

add log check for bj edit

---

src/commands/sex.ts

whoopsies! put false outside the parenthesis instead of inside
i went back and checked and i didnt do this anywhere else on accident
closes #2085

fix: $sex showing false as username sometimes

---

CHANGELOG.md
src/commands/mines.ts

adds random 'cash' spawn that gives 0.33 - 1.33x your bet
and gets rid of silly map and throws object around to different functions

add 'cash' to mines

---

src/commands/market.ts

feat: show item count in market multi

---

src/commands/x.ts

obviously do the thing first i hope i dont have to tell you that

remove temp guild role fix
