- commands/kicksince.js
Fixes an issue where the members filter would only account for users created before the duration specified in the command. Now it correctly filters the members by their joinedTimestamp.
> Change createdAt to joinedTimestamp

- src/commands/timeago.ts
- src/commands/timeuntil.ts
- src/utils/functions/date.ts
- feat: support dayjs date on formatdate func
- feat: add 'long' arg to mstotime func
- fix: mstotime output
- feat: timeuntil command
- feat: timeago command
- fix: prevent date being in the past
> feat: timeago and timeuntil commands

- src/commands/reseteco.ts
makes it so the reseteco command will correctly say that it will keep karma and prestige, instead of only prestige
> fix: reseteco except prestige and karma

- src/commands/daily.ts
- src/commands/weekly.ts
Change from "patreon only" to "premium only" due to there being also being ko-fi etc.
> refactor: change patreon -> premium

- economy/seasons.md
this fixes the typo in the guilds page, to remove the unnecessary and quite gobsmacking error you've made when you were making the docs. i expect better next time, and i want a written apology in my discord dms.
> docs: fix typo

- src/commands/disablecommand.ts
this fixes nypsi's **$disablecmd reset** command to actually say it's been reset, instead of saying "disabled commands have been" without anything else
> fix: $disablecmd reset returns incomplete message

- src/commands/boosters.ts
this removes the **$boosters** command from the nsfw category and puts it in the economy/money category instead
> fix: remove boosters from nsfw category

- SETUP.md
this adds the **$ npx prisma migrate dev** step to the selfhost guide, which gets the prisma/postgresql database populated and ready for data to be added to the database
> docs: add missing step to selfhost setup

- src/commands/daily.ts
Change daily countdown to reset at the beginning of each day instead of having to do it exactly every 24h to stay on track
> change how daily works

- src/commands/minecraft.ts
remove the "/server ip" part of the embed when you don't enter any arguments, since they aren't supported anymore
> fix: remove server ip from $minecraft

- src/commands/poll.ts
this fixes the duplicate name on **$embed**, and shows the main website for nypsi in the footer (replacing the username of the command author).
> refactor: remove footer of $poll

- data/notifications.json
- prisma/schema.prisma
- src/commands/settings.ts
- src/scheduled/clusterjobs/workers.ts
- src/utils/functions/users/notifications.ts
default worker notification behaviour will now only notify user when all workers are full, can be changed to disabled, or to have all notifications
> feat: worker notifications only when full

- package-lock.json
- package.json
- prisma/schema.prisma
- src/commands/blackjack.ts
- src/commands/guild.ts
- src/commands/highlow.ts
- src/commands/minesweeper.ts
- src/commands/rob.ts
- src/commands/rockpaperscissors.ts
- src/commands/roulette.ts
- src/commands/slots.ts
- src/commands/yablon.ts
- src/utils/Constants.ts
- src/utils/functions/economy/balance.ts
- src/utils/functions/economy/guilds.ts
adds guild deposit confirmation
reduces guild members per level
slight decrease to upgrade requirements
ups max level to 69 (practically impossible with current requirements)
prevents guild create abuse to get basic crates
> feat: guild levels update

- src/utils/functions/moderation/logs.ts
modlog embeds wouldn't send when a moderation action was taken
> fix: modlog embeds not sending

- src/commands/mines.ts
gems would add 3 to your win total, instead of the increment + 3. for example, you'd win 3x on a 23 mine game instead of 15x+3x (18x)
> fix: gems not adding your increment

- data/items.json
blue gem now has "blue" as an alias because people are lazy and every other gem is like that
> fix: blue gem alias

- src/commands/ecohistory.ts
this adds the **$graph karma** command to the **$ecohistory** help command as it wasn't previously there since the command was added
> refactor: add graph karma command to ecohistory help

- src/events/message.ts
this includes a link to the discord server even if the person is on a support request cooldown
> refactor: include discord server link on support cooldown

- src/commands/auction.ts
big mod wasn't added to the roles list that could delete auctions for some reason
> fix: allow big mod to delete auctions

- src/utils/functions/economy/balance.ts
you were only counting the price of the highest level upgrade purchased + didnt count price to buy the worker
(started with 300m)
before
after
> fix: wildly inaccurate worker net calculation

- src/commands/item.ts
The brackets for worth were shifted 2 spaces too far to the right, causing the below output for the item command.
This change will clean this up and also fix the markdown for the unvalued link.
> fix: bracket outside conditional thing

- data/workers.json
- nerf wup/tup chances from scrapyard
- tup: -25%
- wup: -50%
- adjust the amount of 🔩 found
- without upgrades: 50 -> 125 (+150%)
- with upgrades, no gems: 250 -> 250 (no change)
- with upgrades, all gems and heart: 462 -> 373 (-19%)
- buff value of 🔩 by 20% to slightly compensate for reduced car parts
> Nerf scrapyard wup/tup chances

- src/scheduled/jobs/premiumexpire.ts
- src/utils/functions/economy/utils.ts
- src/utils/functions/premium/premium.ts
on expire, premium tier gets set to 0. premium data is deleted when tier = 0 on new season
original:
This additions makes so that after user premium subscription expires it sets their premium level to 0 but reserves the premium data for 21 days in case the user would like to renew their premium after expiration. 
Any changes or something you like for me to change lmk
closes #1841
> don't delete premium data on expire

- src/commands/premium.ts
- src/commands/top.ts
- src/utils/handlers/commandhandler.ts
closes #1843 
also allows for cmd aliases to be used when making an alias and on $top cmd
also, empty commands will no longer show the custom alias message so people just typing like "?" (not trynig to do a command) wont get a random error message
> fix: premium alises stripping all whitespace

- src/commands/avatarhistory.ts
- src/commands/captchatest.ts
- src/commands/case.ts
- src/commands/logsearch.ts
- src/commands/market.ts
- src/interactions/market_one.ts
- src/utils/functions/captcha.ts
- src/utils/functions/guilds/evidence.ts
- src/utils/functions/users/commands.ts
works for both the buttons through `$mk -> manage -> create` and `$mk c <item> <b/s> <price>`
if youre confused why i made a bunch of things not edit reply and stuff i had to move the defer reply to later in the code to make sure i didnt have a random ephemeral thinking on the price confirm in the `$mk -> manage -> create path`
through the command works as it did with auctions, shows an expired message
if it expires/is cancelled through `$mk -> manage -> create path`, it just resets the embed to the manage menu
> feat: add market order price confirmations

- CHANGELOG.md
- data/items.json
- prisma/migrations/20250618034837_marriage/migration.sql
- prisma/schema.prisma
- src/commands/divorce.ts
- src/commands/marry.ts
- src/commands/profile.ts
- src/utils/Constants.ts
- src/utils/functions/users/marriage.ts
- src/utils/functions/users/utils.ts
closes #1823
requires a ring to marry someone (is consumed on proposal) (given back if response expires)
if no (broken ring is given to the proposer)
if yes
when confirming divorce (ring is given to divorce target)
marriage is shown in profile under gem line
> feat: add marriage functionality

- src/utils/functions/member.ts
fixes an issue when undefined is passed in after no one completes a lootdrop and errors
i dont think this fixes some lootdrops not responding, but i cant replicate it. i did multiple loot drops on my bot and didnt get a single error one
> fix: try/catch for incorrect MemberResolvable/undefined

- CHANGELOG.md
- src/commands/achievements.ts
numbers can now also be used in search
when searching without supplying a number, itll now default to the current stage you're working on
and pages added to make it easier to look at achievement progression
> feat: add pages to $ach view + better searching
